### ISSUE TITLE
Add more information to the bill of materials in documentation

### ISSUE THREAD

**Issue by galciu** [aetas/mqgateway#26]
Dear Mariusz,
do You have more precise BOM than this one:

https://mqgateway.com/hardware/components/
?
So it'll be easier to search for exact components that You used.

Like first position:

this one:
https://pl.farnell.com/wurth-elektronik/694106301002/connector-power-entry-jack-3a/dp/2472149?mckv=sGuLlreIq_dc|pcrid|491302916621|plid||kword||match||slid||product|2472149|pgrid|115905809683|ptaid|pla-892249581016|&CMP=KNC-GPL-GEN-SHOPPING-Connectors-DoublePresence_13_01_2021

or this one:
https://pl.farnell.com/schurter/4840-2201/dc-power-jack-2p-2a-12v-pcb/dp/3282173?mckv=sb0HyffmN_dc|pcrid|491302916621|plid||kword||match||slid||product|3282173|pgrid|115905809683|ptaid|pla-637698714168|&CMP=KNC-GPL-GEN-SHOPPING-Connectors-DoublePresence_13_01_2021

**Comment by jozala** [comment]
[BOM part of documentation](https://mqgateway.com/hardware/bill-of-materials/) has been now improved (e.g. links are added). 
More detailed BOM files are available on GitHub for MqGateway [Mainboard](https://github.com/aetas/MqGateway-PCB/blob/main/MqGateway/MqGateway_BOM.csv) and [I/O Expander](https://github.com/aetas/MqGateway-PCB/blob/main/IO_Expander/IO_Expander_BOM.csv).

I am closing this ticket. I hope this is enough. Let me know if you need more information.
