### ISSUE TITLE
I/O Expander Board - release date 

### ISSUE THREAD

**Issue by galciu** [aetas/mqgateway#27]
Dear Mariusz,

on the site it says WIP
https://mqgateway.com/hardware/io-expander-board/

but on GIT there are files for expander, are this files ready? 
Can I use them?

PS
Project looks awesome! :)

**Comment by jozala** [comment]
I've added more documentation about I/O Expander Board.
See here: https://mqgateway.com/hardware/io-expander-board/

I am closing this ticket for now.
Please let me know if you need more information.
