### ISSUE TITLE
Control by REST API or WebSocket

### ISSUE THREAD

**Issue by jozala** [aetas/mqgateway#4]
Currently devices can be controlled only through MQTT. Aim of this task is to provide control by REST API. Micronaut should probably be used for small footprint. 
It may be also valuable to use dependency injection from Micronaut if it will be used in project anyway.

**Comment by maniekq** [comment]
It would be nice if MqGateway would use Avahi/Zeroconf to publish their existence in the network.

**Comment by jozala** [comment]
It has been decided to use WebSocket communication only. REST would need long polling or polling which is suboptimal.

**Comment by jozala** [comment]
It has been now implemented
